### ISSUE TITLE
mergerfs.fsck - FileNotFound Error

### ISSUE THREAD

**Issue by dma9** [trapexit/mergerfs-tools#137]
Hi there. I was just trying to run `mergerfs.fsck -v -f manual [mountpoint]`. It has worked fine in the past, but today I got the following error:

`Traceback (most recent call last):
  File "/usr/local/bin/mergerfs.fsck", line 225, in <module>
    main()
  File "/usr/local/bin/mergerfs.fsck", line 209, in main
    check_consistancy(fulldirpath,verbose,size,fix)
  File "/usr/local/bin/mergerfs.fsck", line 149, in check_consistancy
    paths = lgetxattr(fullpath,"user.mergerfs.allpaths")
  File "/usr/local/bin/mergerfs.fsck", line 46, in lgetxattr
    raise IOError(err,os.strerror(err),path)
FileNotFoundError: [Errno 2] No such file or directory: b'[filename]`

Any suggestions on how this could be remedied would be most appreciated.

**Comment by dma9** [comment]
Not sure if it's worth mentioning, but I also get the same error when running mergerfs.dedup on the same file.

**Comment by trapexit** [comment]
I need to know what the details of the file is. As the error says it is claiming it doesn't exist.

**Comment by dma9** [comment]
Thanks for the note. The mountpoint is '/data'. The full filename as shown in the error message is '/data/music/Royksopp - Profound Mysteries III [WEB-FLAC 24-44.1]/R\\udcf6yksopp - Profound Mysteries III [WEB-FLAC 24-44.1]'.

However, when I go to '/data/music/Royksopp - Profound Mysteries III [WEB-FLAC 24-44.1]/', the file (or rather directory) shows up as 

'drwxrwxrwx  2 100108 container-data 4.0K Dec 16 01:12 'R'$'\366''yksopp - Profound Mysteries III [WEB-FLAC 24-44.1]'

I couldn't figure out how to cd into that directory. I imagine this was some sort of corruption in the directory name. Ended up just deleting that directory and then mergerfs.fsck ran fine.
