### ISSUE TITLE
Import Error when trying to run mergerfs.balance

### ISSUE THREAD

**Issue by spikked27** [trapexit/mergerfs-tools#150]
`root@PurpleCloud:~# mergerfs.balance -p 75  /mnt/addons/Frigate_Recordings
Traceback (most recent call last):
  File "/usr/bin/mergerfs.balance", line 18, in <module>
    import ctypes
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory`

**Comment by trapexit** [comment]
That looks like your Python install is messed up.

**Comment by spikked27** [comment]
> That looks like your Python install is messed up.

I installed python through NerdTools on Unraid, are there any dependencies I might be missing?
