### ISSUE TITLE
UnicodeEncodeError: 'utf-8' codec can't encode characters

### ISSUE THREAD

**Issue by ShapeShifter499** [trapexit/mergerfs-tools#43]
I'm trying to make use of this on my server running Arch Linux and I get the following error message. Not really sure what this means, can someone please help?

```
[root@kumo ]# mergerfs.fsck /usr/share/webapps/nextcloud/data 
Traceback (most recent call last):
  File "/usr/bin/mergerfs.fsck", line 213, in <module>
    main()
  File "/usr/bin/mergerfs.fsck", line 202, in main
    check_consistancy(fullpath,verbose,size,fix)
  File "/usr/bin/mergerfs.fsck", line 148, in check_consistancy
    paths = lgetxattr(fullpath,"user.mergerfs.allpaths")
  File "/usr/bin/mergerfs.fsck", line 29, in lgetxattr
    path = path.encode('utf8')
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 117-118: surrogates not allowed
```

**Comment by trapexit** [comment]
Appears the path is has a file or directory with non UTF8 chars. I'll have to see how to go about handling that.

**Comment by ShapeShifter499** [comment]
I suppose it's possible, some of these files came from my Android Phone and from older Linux systems I was running.

**Comment by trapexit** [comment]
Try the newest version I just uploaded.

**Comment by ShapeShifter499** [comment]
testing it now

**Comment by ShapeShifter499** [comment]
I ran 'mergerfs.fsck /usr/share/webapps/nextcloud/data/' with the latest update and there were no output messages or errors. I'm guessing I should only see output when there is an issue right?

**Comment by trapexit** [comment]
No output means it didn't find any issues. And yes, if the issue was still there it'd error.

**Comment by trapexit** [comment]
No problem. Feel free to reach out again if you run across any issues.
