### ISSUE TITLE
mergerfs.dup AttributeError

### ISSUE THREAD

**Issue by maxiedaniels** [trapexit/mergerfs-tools#50]
I'm running mergerfs.dup and showing this error a few minutes into running:

`sending incremental file list
Backup/_CCC SafetyNet/2016-03-29 (March 29) 13-54-57/Users/myusername/._.DS_Store
          4,096 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/6)
Traceback (most recent call last):
  File "./mergerfs.dup", line 181, in <module>
    main()
  File "./mergerfs.dup", line 161, in main
    allpaths = allpaths.split(b'\0')
AttributeError: 'NoneType' object has no attribute 'split'`

**Comment by trapexit** [comment]
Is there a symlink in that directory?

**Comment by magma1447** [comment]
I am having the same issue. What I am duplicating is backups, with plenty of symlinks pointing to files that doesn't exist, at least not in the paths the symlinks are pointing to.

The traceback from duplicating the whole directory looks like this:
`Traceback (most recent call last):
  File "/usr/local/src/mergerfs-tools/mergerfs-tools/src/mergerfs.dup", line 181, in <module>
    main()
  File "/usr/local/src/mergerfs-tools/mergerfs-tools/src/mergerfs.dup", line 161, in main
    allpaths = allpaths.split(b'\0')
AttributeError: 'NoneType' object has no attribute 'split'
`

When duplicating a (broken) symlink only it looks different though.
`Traceback (most recent call last):
  File "/usr/local/src/mergerfs-tools/mergerfs-tools/src/mergerfs.dup", line 181, in <module>
    main()
  File "/usr/local/src/mergerfs-tools/mergerfs-tools/src/mergerfs.dup", line 150, in main
    srcmounts = mergerfs_srcmounts(ctrlfile)
  File "/usr/local/src/mergerfs-tools/mergerfs-tools/src/mergerfs.dup", line 69, in mergerfs_srcmounts
    srcmounts = lgetxattr(ctrlfile,b'user.mergerfs.srcmounts')
  File "/usr/local/src/mergerfs-tools/mergerfs-tools/src/mergerfs.dup", line 47, in lgetxattr
    raise IOError(err,os.strerror(err),path)
OSError: [Errno 14] Bad address
`

**Comment by trapexit** [comment]
I've not had the chance to look at this.

MergerFS offers special xattrs which provide metadata about the file. The code doesn't properly manage pointing to a file which doesn't have those.

**Comment by eduncan911** [comment]
@maxiedaniels just fyi, i disable `. DS_Store` on my macOS machines - so i don't get those hidden files.

You still need to search and destroy them within your pool though.
